### ISSUE TITLE
OpenMC offloading crashes on GTX 1660 GPU

### ISSUE THREAD

**Issue by AI-Pranto** [jtramm/openmc_offloading_builder#1]
Hi @jtramm,

I am trying to install OpenMC with GPU  offloading support on my NVIDIA GTX 1660 GPU (`Driver:470.141.03`, `CUDA: 11.2`) however, running `openmc_offloading_benchmarks/progression_tests/small` problem terminates with the following error message. 

```bash
Thread 10 "openmc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc27f8d40 (LWP 53564)]
0x00007ffff7b9fe58 in openmc::IncoherentInelasticAEFlat::sample(double, double&, double&, unsigned long*) const () from /home/pranto/opt/openmc_gpu/openmc_install/lib/libopenmc.so
(gdb)
```

The PRESET_CXX_FLAGS for my GPU were `-fopenmp-targets=nvptx64 -Xopenmp-target -march=sm_75`

What could be the problem? And How to fix it?
Thanks

**Comment by jtramm** [comment]
Hey @AI-Pranto -- thanks for reaching out! I haven't seen this particular seg fault before, but here are some thoughts:

- Can you share more info about which compiler (and what version) you're using?
- How you are launching openmc? What happens if it is run as: ```OMP_TARGET_OFFLOAD=MANDATORY openmc --event```
- It would be useful to see the full cmake command you are using along with all the cmake output and OpenMC compilation output.

**Comment by jtramm** [comment]
Oh -- another thing that comes to mind: what XS data set are you using? I have actually seen some segmentation faults in the reaction portions of the code with certain data sets. The one that gets downloaded as part of this script seems to work correctly though. We are working to figure out the issue with other XS data libraries.

**Comment by AI-Pranto** [comment]
I've tried two XS data libraries (`jeff-3.3-hdf5` and `endfb-vii.1-hdf5`)so far, and they all have the same problems. But after switching to the `nndc-hdf5` data library, I was able to run openmc without any issues.

**Comment by AI-Pranto** [comment]
BTW, thanks @jtramm!
